[[ISSUERS]]
address = "rJDuRkE6PNorR58BogAkdM5ApFx9VSeePy"
name = "MOON"

[[TOKENS]]
issuer = "rJDuRkE6PNorR58BogAkdM5ApFx9VSeePy"
currency = "MOON"
name = "MOON"
desc = "Digital gold on XRPL"
icon = "https://metadata.moonbase.org/logo.png"

[[TOKENS.URLS]]
url = "https://metadata.moonbase.org"
type = "website"

[[TOKENS.URLS]]
url = "https://x.com/moonxrpl"
type = "social"
